### ISSUE TITLE
How to test an app using this?

### ISSUE THREAD

**Issue by bobmazanec** [adamniedzielski/sidekiq-staged_push#13]
Hi, again.

I hope a question about testing an app using `sidekiq-staged_push` is appropriate here 🙏.

I'd like to test that jobs get scheduled with the correct arguments.

So far, I haven't found a way to make things like `Sidekiq::Testing.fake!` work for me—e.g.,

```
[...]
expect {
  # something that enqueues a MyJob
}.must_differ "MyJob.jobs.size", +1
```

fails with

```
"MyJob.jobs.size" didn't change by 1.
Expected: 1
  Actual: 0
```

So I've been using (MiniTest) mocking—e.g.,

```
[...]
# expect SomeJob.perform(some_arg) to call
# OtherJob.perform_async(some_arg)
mock_perform_async.expect :call, mock_perform_async, [some_arg]
OtherJob.stub :perform_async, mock_perform_async do
  SomeJob.perform_inline some_arg
end

mock_perform_async.verify
```

but when I got to something that calls `SomeJob.perform_at`, I found I also have to mock its `:tap`
Easy enough, but it feels more and more "inside baseball".

Am I missing something?

Thanks

**Comment by bobmazanec** [comment]
Sorry—looked past examining `Sidekiq::StagedPush::StagedJob`s
`payload` seems to have everything I want
It still seems a _little_ "implementation detail"y, but better than the mocking above.
Also lets me confirm when jobs are/not committed

Comments/insights still welcome—especially if I'm still missing / looking past something(s)!

**Comment by bobmazanec** [comment]
Might you be open to adding test support to the gem to help avoid pushing knowledge of the implementation details into client app testing?

Playing around with this today (and learning about adding custom Minitest assertions/expectations), I got `assert_enqueues_staged_job`/`must_enqueue_staged_job` & `assert_enqueues_staged_jobs` / `must_enqueue_staged_jobs` some flavor of "working", allowing this kind of thing:

```
describe SomeJob, :job do
  context "given some pre-conditions" do
    # set them up...

    it "schedules an OtherJob" do
      expect {
        SomeJob.perform_inline some_object.id
      }.must_enqueue_staged_job(
        class: "OtherJob",
        args: [some_object.id, some_other_value]
      )
    end
  end

  context "given some other pre-conditions" do
    # set them up...

    it "schedules an OtherJob and a StillAnotherJob" do
      expect {
        SomeJob.perform_inline some_object.id
      }.must_enqueue_staged_jobs({
        class: "OtherJob",
        args: [some_object.id, some_other_value]
      },
      {
        class: "StillAnotherJob",
        args: [some_object.id, still_another_value]
      })
    end
  end
end
```

There is *lots* of room to negotiate (improve?) assertion/expectation names, what arguments to pass & how, how failed assertions/expectations are reported, etc., of course. This was simply what I got working today; I wanted to open the conversation before extracting it from my project, cleaning it up, and working up a PR, etc.

I notice you use Rspec in this project.
I'm an Rspec fan and normally use it...but I decided to "force myself" to use & learn about Minitest in this app/project, so that's where I've started 🤷‍♂️. Happy to talk about custom matchers, too.

**Comment by adamniedzielski** [comment]
Hey @bobmazanec 👋 I can see that you invested quite some time into researching the topic 👏 👏 

Yes indeed, I see examining `Sidekiq::StagedPush::StagedJob` and its `payload` as the way to go when testing an application that uses this gem. I think that the popularity and the size of this gem doesn't justify adding custom matchers to the project. However, if you'd like to add an explanation to the README I'll accept the PR 🙂
