### ISSUE TITLE
enqueuer.rb:36:in `primary_process?': undefined method `leader?' for Sidekiq::Senate:Class (NoMethodError)

### ISSUE THREAD

**Issue by Aubermean** [adamniedzielski/sidekiq-staged_push#17]
`Sidekiq::Senate.leader?` no longer works since 6.5.

[see this issue](https://github.com/sidekiq/sidekiq/issues/5425)

**Comment by Aubermean** [comment]
Sidekiq's creator just freshed up the Wiki for this: https://github.com/sidekiq/sidekiq/wiki/Ent-Leader-Election

**Comment by adamniedzielski** [comment]
Thank you for reporting @Aubermean 🙌 I currently don't have access to Sidekiq Enterprise to properly test the fix. Would you like to submit a PR that fixes the issue?
